window.APP_DATA = {
  datasetsMeta: {
    odhObjects: {
      label: "Объекты ОДХ",
      type: "object",
      attributes: [
        { code: "objectId", label: "Идентификатор", type: "number" },
        { code: "oghId", label: "ИД ОГХ", type: "number" },
        { code: "objectType", label: "Тип ОГХ", type: "text" },
        { code: "name", label: "Наименование", type: "text" },
        { code: "startDate", label: "Дата начала", type: "date" },
        { code: "endDate", label: "Дата окончания", type: "date" },
        { code: "status", label: "Статус", type: "text" },
        { code: "versionId", label: "ID версии", type: "number" },
        { code: "address", label: "Адрес", type: "text" },
        { code: "district", label: "Округ", type: "text" },
        { code: "area", label: "Район", type: "text" },
        { code: "department", label: "Ведомственный ОИВ", type: "text" },
        { code: "balanceHolder", label: "Балансодержатель", type: "text" },
        { code: "customer", label: "Заказчик", type: "text" },
        { code: "cleaningCategoryCode", label: "Код категории по уборке", type: "number" },
        { code: "cleaningCategoryName", label: "Наименование категории ОДХ", type: "text" },
        { code: "objectArea", label: "Площадь", type: "number" },
        { code: "actualArea", label: "Площадь ОГХ рассчит. (актуальная)", type: "number" }
      ]
    },
    odhWorks: {
      label: "Работы на ОДХ",
      type: "work",
      attributes: [
        { code: "roadAreaAllYears", label: "Площадь дороги (за все годы), площадь", type: "number" },
        { code: "roadCountAllYears", label: "Количество дороги (за все годы), количество", type: "number" },
        { code: "roadCountAllYearsOver15", label: "Количество дороги (за все годы), количество больше 15", type: "number" },
        { code: "roadYear2016Area", label: "Дороги 2016, площадь", type: "number" },
        { code: "roadYear2017Area", label: "Дороги 2017, площадь", type: "number" },
        { code: "roadYear2018Area", label: "Дороги 2018, площадь", type: "number" },
        { code: "roadYear2019Area", label: "Дороги 2019, площадь", type: "number" },
        { code: "roadYear2020Area", label: "Дороги 2020, площадь", type: "number" },
        { code: "roadYear2021Area", label: "Дороги 2021, площадь", type: "number" },
        { code: "roadYear2022Area", label: "Дороги 2022, площадь", type: "number" },
        { code: "roadYear2023Area", label: "Дороги 2023, площадь", type: "number" },
        { code: "roadYear2024Area", label: "Дороги 2024, площадь", type: "number" },
        { code: "roadYear2025Area", label: "Дороги 2025, площадь", type: "number" },
        { code: "roadYear2026Area", label: "Дороги 2026, площадь", type: "number" },
        { code: "plan2026Roads", label: "Наличие плана на 2026 (дороги)", type: "boolean" },
        { code: "plan2027Roads", label: "Наличие плана на 2027 (дороги)", type: "boolean" },
        { code: "roadInterrepairViolation", label: "Нарушение межремонтного срока (дороги)", type: "boolean" },
        { code: "lastWorkYear", label: "Последний год работ", type: "number" }
      ]
    },
    okbWorks: {
      label: "Работы на ОКБ",
      type: "work",
      attributes: [
        { code: "okbCountAllYears", label: "Количество по годам ОКБ, количество", type: "number" },
        { code: "okbCountAllYearsOver15", label: "Количество по годам ОКБ, количество больше 15", type: "number" },
        { code: "allWorksCount", label: "Количество по годам все, количество", type: "number" },
        { code: "allWorksCountOver15", label: "Количество по годам все, количество больше 15", type: "number" },
        { code: "lastYearOver15RoadsOkb", label: "Последний год больше 15 (дороги и ОКБ) до 27 года вкл", type: "number" },
        { code: "lastWorkYearOver15Until25", label: "Последний год работ процент больше 15 до 25 года вкл (дороги и ОКБ)", type: "number" },
        { code: "planYearWithTerm", label: "Срок + год (до 25 года вкл) больше 15 процентов", type: "number" },
        { code: "noImprovementOver15", label: "Благо не проводилось больше 15 до 2025 вкл (дороги и ОКБ)", type: "boolean" },
        { code: "lastWorkYearUntil25All", label: "Последний год работ процент больше 15 до 25 года вкл (ВСЕ)", type: "number" },
        { code: "noImprovementAll", label: "Благо не проводилось больше 15 (ВСЕ)", type: "boolean" },
        { code: "interrepairTerm", label: "Межремонтный срок", type: "number" },
        { code: "noImprovementUntil25", label: "Благо не проводилось до 2025 года вкл (ОКБ и ОДХ)", type: "boolean" }
      ]
    }
  },

  weightableFields: [
    { code: "coveragePercent", label: "Процент покрытия" },
    { code: "repairAge", label: "Давность последнего ремонта" },
    { code: "estimatedCost", label: "Ориентировочная стоимость" },
    { code: "recommendedVolume", label: "Рекомендуемый объем работ" }
  ],

  baseWeights: {
    coveragePercent: 35,
    repairAge: 25,
    estimatedCost: 20,
    recommendedVolume: 20
  },

  objects: [
    {
      objectId: 10001092,
      oghId: 10001092,
      objectType: "Объект дорожного хозяйства",
      name: "Антонова-Овсеенко улица",
      startDate: "2021-08-06",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 842613794,
      address: "Шмитовский проезд",
      district: "ЦАО",
      area: "Пресненский",
      department: "Префектура ЦАО",
      balanceHolder: "Жилищник Пресненский",
      customer: "Жилищник Пресненский",
      cleaningCategoryCode: 4,
      cleaningCategoryName: "Улицы районного значения",
      objectArea: 5494.43,
      actualArea: 5494.43,

      roadAreaAllYears: 3468.72,
      roadCountAllYears: 4,
      roadCountAllYearsOver15: 3,
      roadYear2016Area: 0,
      roadYear2017Area: 0,
      roadYear2018Area: 0,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 980.50,
      roadYear2022Area: 0,
      roadYear2023Area: 1120.60,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 0,
      plan2026Roads: true,
      plan2027Roads: false,
      roadInterrepairViolation: false,
      lastWorkYear: 2023,

      okbCountAllYears: 1,
      okbCountAllYearsOver15: 1,
      allWorksCount: 5,
      allWorksCountOver15: 4,
      lastYearOver15RoadsOkb: 2023,
      lastWorkYearOver15Until25: 2023,
      planYearWithTerm: 2026,
      noImprovementOver15: false,
      lastWorkYearUntil25All: 2023,
      noImprovementAll: false,
      interrepairTerm: 5,
      noImprovementUntil25: false,

      coveragePercent: 46.6,
      coveredArea: 1600,
      uncoveredArea: 1840,
      recommendedVolume: 1600,
      estimatedCost: 5120000,
      repairAge: 3,
      reason: "Покрытие ниже порога",
      sourceType: "Объекты ОДХ",
      geometry: [[55.75755, 37.53558],[55.75773, 37.53657],[55.75678, 37.53975],[55.75584, 37.53867]]
    },
    {
      objectId: 10003427,
      oghId: 10003427,
      objectType: "Объект дорожного хозяйства",
      name: "Новочеркасский бульвар",
      startDate: "2020-04-12",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 927761112,
      address: "Новочеркасский бульвар",
      district: "ЮВАО",
      area: "Марьино",
      department: "Префектура ЮВАО",
      balanceHolder: "ГБУ Автомобильные дороги ЮВАО",
      customer: "ГБУ Автомобильные дороги ЮВАО",
      cleaningCategoryCode: 2,
      cleaningCategoryName: "Городские магистрали",
      objectArea: 8912.10,
      actualArea: 8912.10,

      roadAreaAllYears: 4125,
      roadCountAllYears: 3,
      roadCountAllYearsOver15: 2,
      roadYear2016Area: 0,
      roadYear2017Area: 0,
      roadYear2018Area: 1250,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 0,
      roadYear2022Area: 0,
      roadYear2023Area: 1620,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 0,
      plan2026Roads: true,
      plan2027Roads: true,
      roadInterrepairViolation: true,
      lastWorkYear: 2023,

      okbCountAllYears: 0,
      okbCountAllYearsOver15: 0,
      allWorksCount: 3,
      allWorksCountOver15: 2,
      lastYearOver15RoadsOkb: 2023,
      lastWorkYearOver15Until25: 2023,
      planYearWithTerm: 2025,
      noImprovementOver15: false,
      lastWorkYearUntil25All: 2023,
      noImprovementAll: false,
      interrepairTerm: 3,
      noImprovementUntil25: false,

      coveragePercent: 57.0,
      coveredArea: 3520,
      uncoveredArea: 2650,
      recommendedVolume: 2650,
      estimatedCost: 8470000,
      repairAge: 3,
      reason: "Недостаточное покрытие, требуется планирование",
      sourceType: "Работы на ОДХ",
      geometry: [[55.65364, 37.74556],[55.65456, 37.75120],[55.65250, 37.75311],[55.65150, 37.74720]]
    },
    {
      objectId: 10006649,
      oghId: 10006649,
      objectType: "Объект дорожного хозяйства",
      name: "Подъезд к жилым корпусам",
      startDate: "2019-05-16",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 782441105,
      address: "Молодогвардейская улица",
      district: "ЗАО",
      area: "Кунцево",
      department: "Префектура ЗАО",
      balanceHolder: "ГБУ Жилищник Кунцево",
      customer: "ГБУ Жилищник Кунцево",
      cleaningCategoryCode: 5,
      cleaningCategoryName: "Проезды локального значения",
      objectArea: 4220.80,
      actualArea: 4220.80,

      roadAreaAllYears: 0,
      roadCountAllYears: 0,
      roadCountAllYearsOver15: 0,
      roadYear2016Area: 0,
      roadYear2017Area: 0,
      roadYear2018Area: 0,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 0,
      roadYear2022Area: 0,
      roadYear2023Area: 0,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 0,
      plan2026Roads: false,
      plan2027Roads: false,
      roadInterrepairViolation: true,
      lastWorkYear: null,

      okbCountAllYears: 2,
      okbCountAllYearsOver15: 1,
      allWorksCount: 2,
      allWorksCountOver15: 1,
      lastYearOver15RoadsOkb: 2022,
      lastWorkYearOver15Until25: 2022,
      planYearWithTerm: 2024,
      noImprovementOver15: false,
      lastWorkYearUntil25All: 2022,
      noImprovementAll: false,
      interrepairTerm: 3,
      noImprovementUntil25: false,

      coveragePercent: 22.4,
      coveredArea: 940,
      uncoveredArea: 3280,
      recommendedVolume: 3280,
      estimatedCost: 10496000,
      repairAge: 0,
      reason: "Работы на дорогах не выполнялись, есть следы ОКБ",
      sourceType: "Работы на ОКБ",
      geometry: [[55.72850, 37.3921],[55.7293, 37.3969],[55.7269, 37.3992],[55.7258, 37.3943]]
    },
    {
      objectId: 10023123,
      oghId: 10023123,
      objectType: "Объект дорожного хозяйства",
      name: "Проезд у школы",
      startDate: "2022-02-01",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 1002312301,
      address: "Школьная улица",
      district: "САО",
      area: "Головинский",
      department: "Префектура САО",
      balanceHolder: "ГБУ Жилищник Головинский",
      customer: "ГБУ Жилищник Головинский",
      cleaningCategoryCode: 4,
      cleaningCategoryName: "Улицы районного значения",
      objectArea: 3775.30,
      actualArea: 3775.30,

      roadAreaAllYears: 1480,
      roadCountAllYears: 2,
      roadCountAllYearsOver15: 1,
      roadYear2016Area: 0,
      roadYear2017Area: 0,
      roadYear2018Area: 0,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 0,
      roadYear2022Area: 0,
      roadYear2023Area: 1480,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 820,
      plan2026Roads: true,
      plan2027Roads: false,
      roadInterrepairViolation: false,
      lastWorkYear: 2023,

      okbCountAllYears: 0,
      okbCountAllYearsOver15: 0,
      allWorksCount: 2,
      allWorksCountOver15: 1,
      lastYearOver15RoadsOkb: 2023,
      lastWorkYearOver15Until25: 2023,
      planYearWithTerm: 2028,
      noImprovementOver15: false,
      lastWorkYearUntil25All: 2023,
      noImprovementAll: false,
      interrepairTerm: 5,
      noImprovementUntil25: false,

      coveragePercent: 71.0,
      coveredArea: 2680,
      uncoveredArea: 1095.3,
      recommendedVolume: 1095.3,
      estimatedCost: 3504960,
      repairAge: 3,
      reason: "Частичное покрытие, есть план 2026",
      sourceType: "Объекты ОДХ",
      geometry: [[55.8512, 37.4978],[55.8520, 37.5020],[55.8497, 37.5038],[55.8489, 37.4994]]
    },
    {
      objectId: 10044567,
      oghId: 10044567,
      objectType: "Объект дорожного хозяйства",
      name: "Территория без ремонта",
      startDate: "2018-09-03",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 1004456701,
      address: "Северная улица",
      district: "СВАО",
      area: "Бибирево",
      department: "Префектура СВАО",
      balanceHolder: "ГБУ Жилищник Бибирево",
      customer: "ГБУ Жилищник Бибирево",
      cleaningCategoryCode: 5,
      cleaningCategoryName: "Проезды локального значения",
      objectArea: 6150.00,
      actualArea: 6150.00,

      roadAreaAllYears: 0,
      roadCountAllYears: 0,
      roadCountAllYearsOver15: 0,
      roadYear2016Area: 0,
      roadYear2017Area: 0,
      roadYear2018Area: 0,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 0,
      roadYear2022Area: 0,
      roadYear2023Area: 0,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 0,
      plan2026Roads: false,
      plan2027Roads: false,
      roadInterrepairViolation: true,
      lastWorkYear: null,

      okbCountAllYears: 0,
      okbCountAllYearsOver15: 0,
      allWorksCount: 0,
      allWorksCountOver15: 0,
      lastYearOver15RoadsOkb: null,
      lastWorkYearOver15Until25: null,
      planYearWithTerm: 2023,
      noImprovementOver15: true,
      lastWorkYearUntil25All: null,
      noImprovementAll: true,
      interrepairTerm: 4,
      noImprovementUntil25: true,

      coveragePercent: 0.0,
      coveredArea: 0,
      uncoveredArea: 6150,
      recommendedVolume: 6150,
      estimatedCost: 19680000,
      repairAge: 0,
      reason: "Неблагоустроенная геометрия без проведенного ремонта",
      sourceType: "Работы на ОКБ",
      geometry: [[55.8899, 37.6012],[55.8910, 37.6074],[55.8884, 37.6094],[55.8872, 37.6031]]
    },
    {
      objectId: 10077881,
      oghId: 10077881,
      objectType: "Объект дорожного хозяйства",
      name: "Внутриквартальный проезд",
      startDate: "2017-03-20",
      endDate: "3000-01-01",
      status: "Действующий",
      versionId: 1007788101,
      address: "Парковая улица",
      district: "ЮАО",
      area: "Царицыно",
      department: "Префектура ЮАО",
      balanceHolder: "ГБУ Автомобильные дороги ЮАО",
      customer: "ГБУ Автомобильные дороги ЮАО",
      cleaningCategoryCode: 5,
      cleaningCategoryName: "Проезды локального значения",
      objectArea: 5120,
      actualArea: 5120,

      roadAreaAllYears: 930,
      roadCountAllYears: 1,
      roadCountAllYearsOver15: 1,
      roadYear2016Area: 0,
      roadYear2017Area: 930,
      roadYear2018Area: 0,
      roadYear2019Area: 0,
      roadYear2020Area: 0,
      roadYear2021Area: 0,
      roadYear2022Area: 0,
      roadYear2023Area: 0,
      roadYear2024Area: 0,
      roadYear2025Area: 0,
      roadYear2026Area: 0,
      plan2026Roads: false,
      plan2027Roads: true,
      roadInterrepairViolation: true,
      lastWorkYear: 2017,

      okbCountAllYears: 0,
      okbCountAllYearsOver15: 0,
      allWorksCount: 1,
      allWorksCountOver15: 1,
      lastYearOver15RoadsOkb: 2017,
      lastWorkYearOver15Until25: 2017,
      planYearWithTerm: 2021,
      noImprovementOver15: true,
      lastWorkYearUntil25All: 2017,
      noImprovementAll: true,
      interrepairTerm: 4,
      noImprovementUntil25: true,

      coveragePercent: 18.2,
      coveredArea: 930,
      uncoveredArea: 4190,
      recommendedVolume: 4190,
      estimatedCost: 13408000,
      repairAge: 9,
      reason: "Истек межремонтный срок, покрытие ниже допустимого",
      sourceType: "Работы на ОДХ",
      geometry: [[55.6224, 37.6663],[55.6234, 37.6717],[55.6208, 37.6738],[55.6196, 37.6679]]
    }
  ]
};
